# Generated by Django 3.2.23 on 2023-11-14 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20231114_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id_character', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('etat', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('race', models.CharField(max_length=30)),
                ('photo', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='AquariumPlace',
            new_name='Equipement',
        ),
        migrations.DeleteModel(
            name='Fish',
        ),
        migrations.AddField(
            model_name='character',
            name='lieu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.equipement'),
        ),
    ]
